CREATE OR REPLACE FUNCTION public.duel_level_stake(p_level text)
 RETURNS numeric
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  SELECT CASE p_level
    WHEN 'ROOKIE I' THEN 5
    WHEN 'ROOKIE II' THEN 10
    WHEN 'ROOKIE III' THEN 15
    WHEN 'GUERRIER DES PAVÉS I' THEN 20
    WHEN 'GUERRIER DES PAVÉS II' THEN 25
    WHEN 'GUERRIER DES PAVÉS III' THEN 30
    WHEN 'MACHINE DE GUERRE I' THEN 40
    WHEN 'MACHINE DE GUERRE II' THEN 45
    WHEN 'MACHINE DE GUERRE III' THEN 50
    WHEN 'FREAK I' THEN 60
    WHEN 'FREAK II' THEN 65
    WHEN 'FREAK III' THEN 70
    WHEN 'FREAK MASTER' THEN 80
    ELSE 5
  END::NUMERIC;
$function$;